import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Urunler extends javax.swing.JFrame {

    /**
     * Creates new form Urunler
     */
    public Urunler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        katigidab = new javax.swing.JButton();
        sivigidab = new javax.swing.JButton();
        temizlikb = new javax.swing.JButton();
        bakimb = new javax.swing.JButton();
        gerib = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ürünler");
        setResizable(false);

        katigidab.setText("Katı Gıdalar");
        katigidab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katigidabActionPerformed(evt);
            }
        });

        sivigidab.setText("Sıvı Gıdalar");
        sivigidab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sivigidabActionPerformed(evt);
            }
        });

        temizlikb.setText("Temizlik");
        temizlikb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizlikbActionPerformed(evt);
            }
        });

        bakimb.setText("Kişisel Bakım");
        bakimb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakimbActionPerformed(evt);
            }
        });

        gerib.setText("Geri");
        gerib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geribActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bakimb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sivigidab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(katigidab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(temizlikb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gerib)
                        .addGap(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(katigidab)
                .addGap(18, 18, 18)
                .addComponent(sivigidab)
                .addGap(18, 18, 18)
                .addComponent(temizlikb)
                .addGap(18, 18, 18)
                .addComponent(bakimb)
                .addGap(29, 29, 29)
                .addComponent(gerib)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void katigidabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katigidabActionPerformed
        dispose();
        try {
            KatiGida kg = new KatiGida();
            kg.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_katigidabActionPerformed

    private void sivigidabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sivigidabActionPerformed
        dispose();
        try {
            SiviGida sg = new SiviGida();
            sg.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sivigidabActionPerformed

    private void temizlikbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizlikbActionPerformed
        dispose();
        try {
            Temizlik t = new Temizlik();
            t.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_temizlikbActionPerformed

    private void bakimbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakimbActionPerformed
        dispose();
        try {
            Bakim b = new Bakim();
            b.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bakimbActionPerformed

    private void geribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geribActionPerformed
        dispose();
        Marketim m = new Marketim();
        m.setVisible(true);
    }//GEN-LAST:event_geribActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urunler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakimb;
    private javax.swing.JButton gerib;
    private javax.swing.JButton katigidab;
    private javax.swing.JButton sivigidab;
    private javax.swing.JButton temizlikb;
    // End of variables declaration//GEN-END:variables
}
